# Generated by Django 3.1.1 on 2020-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20201007_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cart_status',
            field=models.CharField(default='not carted', max_length=120),
        ),
    ]
