# Generated by Django 3.1.1 on 2020-11-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_book_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cart_status',
        ),
    ]
