# Generated by Django 3.1.1 on 2020-10-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderrecieved', 'orderrecieved'), ('deliverd', 'deliverd'), ('dispached', 'dispached')], default='orderrecieved', max_length=120),
        ),
    ]
