# Generated by Django 3.1.1 on 2020-10-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201009_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('deliverd', 'deliverd'), ('orderrecieved', 'orderrecieved'), ('dispached', 'dispached')], default='orderrecieved', max_length=120),
        ),
    ]
