# Generated by Django 3.1.1 on 2020-10-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201010_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderrecieved', 'orderrecieved'), ('deliverd', 'deliverd'), ('dispached', 'dispached')], default='orderrecieved', max_length=120),
        ),
    ]
