# Generated by Django 3.1.1 on 2020-10-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20201012_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.CharField(default='userone', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('dispached', 'dispached'), ('orderrecieved', 'orderrecieved'), ('deliverd', 'deliverd')], default='orderrecieved', max_length=120),
        ),
    ]
