# Generated by Django 3.1.1 on 2020-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20201013_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderrecieved', 'orderrecieved'), ('deliverd', 'deliverd'), ('dispached', 'dispached')], default='orderrecieved', max_length=120),
        ),
    ]
