# Generated by Django 3.1.1 on 2020-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20201014_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('deliverd', 'deliverd'), ('orderrecieved', 'orderrecieved'), ('dispached', 'dispached')], default='orderrecieved', max_length=120),
        ),
    ]
