# Generated by Django 3.1.1 on 2020-10-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20201014_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderrecieved', 'orderrecieved'), ('dispached', 'dispached'), ('deliverd', 'deliverd')], default='orderrecieved', max_length=120),
        ),
    ]
