# Generated by Django 3.1.1 on 2020-10-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120, unique=True)),
                ('ram', models.CharField(max_length=150)),
                ('camera', models.CharField(max_length=150)),
                ('os', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='images')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.brand')),
            ],
        ),
    ]
