# Generated by Django 3.1.1 on 2020-11-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_mobile_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='cart_status',
        ),
    ]
