# Generated by Django 3.1.1 on 2020-11-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_remove_mobile_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='storage',
            field=models.CharField(default='0GB', max_length=150),
            preserve_default=False,
        ),
    ]
