# Generated by Django 3.1.1 on 2020-10-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('productid', models.IntegerField()),
                ('status', models.CharField(choices=[('dispached', 'dispached'), ('orderrecieved', 'orderrecieved'), ('deliverd', 'deliverd')], default='orderrecieved', max_length=120)),
                ('active_status', models.IntegerField(default=1)),
            ],
        ),
    ]
