# Generated by Django 3.1.1 on 2020-11-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart_status',
            field=models.CharField(default='not carted', max_length=120),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('deliverd', 'deliverd'), ('dispached', 'dispached'), ('orderrecieved', 'orderrecieved')], default='orderrecieved', max_length=120),
        ),
    ]
