# Generated by Django 3.1.1 on 2020-11-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201101_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('deliverd', 'deliverd'), ('dispached', 'dispached'), ('orderrecieved', 'orderrecieved')], default='orderrecieved', max_length=120),
        ),
    ]
