# Generated by Django 3.1.1 on 2020-11-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201109_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('dispached', 'dispached'), ('deliverd', 'deliverd'), ('orderrecieved', 'orderrecieved')], default='orderrecieved', max_length=120),
        ),
    ]
