# Generated by Django 3.1.1 on 2020-11-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20201112_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart_status',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderrecieved', 'orderrecieved'), ('deliverd', 'deliverd'), ('dispached', 'dispached')], default='orderrecieved', max_length=120),
        ),
    ]
