# Generated by Django 3.1.1 on 2020-11-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20201112_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderrecieved', 'orderrecieved'), ('dispached', 'dispached'), ('deliverd', 'deliverd')], default='orderrecieved', max_length=120),
        ),
    ]
