# Generated by Django 3.1.1 on 2020-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20201112_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('dispached', 'dispached'), ('orderrecieved', 'orderrecieved'), ('deliverd', 'deliverd')], default='orderrecieved', max_length=120),
        ),
    ]
