# Generated by Django 3.1.1 on 2020-11-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20201116_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderrecieved', 'orderrecieved'), ('deliverd', 'deliverd'), ('dispached', 'dispached')], default='orderrecieved', max_length=120),
        ),
    ]
