# Generated by Django 3.1.1 on 2020-11-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20201116_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('deliverd', 'deliverd'), ('dispached', 'dispached'), ('orderrecieved', 'orderrecieved')], default='orderrecieved', max_length=120),
        ),
    ]
