# Generated by Django 3.1.1 on 2020-11-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20201117_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_name',
            field=models.CharField(default='none', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('orderrecieved', 'orderrecieved'), ('dispached', 'dispached'), ('deliverd', 'deliverd')], default='orderrecieved', max_length=120),
        ),
    ]
